### ISSUE TITLE
Unable to start due to NodeJS issue

### ISSUE THREAD

**Issue by JonaKms** [lutris/web-runner#5]
I've used both the latest version and the LTS version of NodeJS when doing this, and get the same result either way. I use `npm install` then `make`, and when trying to run the built electron application I always get this error.

```
$ /home/jona/Downloads/web-runner/build/web-x86_64/electron/electron
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'is-url-superb'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/home/jona/Downloads/web-runner/build/web-x86_64/electron/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/jona/Downloads/web-runner/build/web-x86_64/electron/resources/app.asar/main.js:6:15)
    at Object.<anonymous> (/home/jona/Downloads/web-runner/build/web-x86_64/electron/resources/app.asar/main.js:184:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```
So I then just scrapped everything then did `npm install` again, but this time I also make sure to `npm install is-url-superb` as well. After confirming is-url-superlib was in the node-modules directory, I `make` and try the newly built application. Yet again getting the same error. Not sure what else to do.

**Comment by JonaKms** [comment]
> I've used both the latest version and the LTS version of NodeJS when doing this, and get the same result either way. I use `npm install` then `make`, and when trying to run the built electron application I always get this error.
> 
> ```
> $ /home/jona/Downloads/web-runner/build/web-x86_64/electron/electron
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module 'is-url-superb'
>     at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
>     at Function.Module._resolveFilename (/home/jona/Downloads/web-runner/build/web-x86_64/electron/resources/electron.asar/common/reset-search-paths.js:43:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:510:25)
>     at Module.require (internal/modules/cjs/loader.js:640:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/home/jona/Downloads/web-runner/build/web-x86_64/electron/resources/app.asar/main.js:6:15)
>     at Object.<anonymous> (/home/jona/Downloads/web-runner/build/web-x86_64/electron/resources/app.asar/main.js:184:3)
>     at Module._compile (internal/modules/cjs/loader.js:693:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
>     at Module.load (internal/modules/cjs/loader.js:602:32)
> ```
> 
> So I then just scrapped everything then did `npm install` again, but this time I also make sure to `npm install is-url-superb` as well. After confirming is-url-superlib was in the node-modules directory, I `make` and try the newly built application. Yet again getting the same error. Not sure what else to do.
