### ISSUE TITLE
Can't build due to Flash player EOL notice

### ISSUE THREAD

**Issue by sethidden** [lutris/web-runner#7]
get-flash-url.js has this line and it tries to curl it
`let jsonurl = https://www.adobe.com/products/flashplayer/end-of-life.html?platform_type=Linux&platform_dist=&platform_arch=x86_64&browser_arch=&browser_type=&browser_vers=&browser_dist=Chrome&eventname=flashplayerotherversions`

But when I visit that site in my browser, it's just an "Adobe Flash Player EOL General Information Page".

This causes make to fail, since it can't download Flash:
<details>
<summary>make logs</summary>

```sh
t430 :: dev/0gitmisc/web-runner » npm install
up to date in 1.156s

13 packages are looking for funding
  run `npm fund` for details

t430 :: dev/0gitmisc/web-runner » make
Building web-x86_64 x86_64
rm -rf "build/web-x86_64"
mkdir: created directory 'build/web-x86_64'
'scripts/launch.sh' -> 'build/web-x86_64/launch.sh'
scripts/build.js x64 9.2.1 && mv -v "build/electron-linux-x64" "build/web-x86_64/electron"
Packaging app for platform linux x64 using electron v9.2.1
renamed 'build/electron-linux-x64' -> 'build/web-x86_64/electron'
mkdir: created directory 'build/web-x86_64/PepperFlash'
Checking flash player version...
/home/artur/dev/0gitmisc/web-runner/scripts/get-flash-url.js:11
  if (err) throw err
           ^

SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at /home/artur/dev/0gitmisc/web-runner/node_modules/simple-get/index.js:85:23
    at PassThrough.<anonymous> (/home/artur/dev/0gitmisc/web-runner/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (events.js:420:28)
    at PassThrough.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
make: *** [Makefile:51: build-x86_64] Error 1
t430 :: dev/0gitmisc/web-runner 2 »
```

</details>

**Comment by strycore** [comment]
I can confirm that I haven't been able to run Flash games with the current web runner. 
I was able to workaround by downgrading to an older version: https://lutris.net/files/runners/web-0.0.9-x86_64.tar.gz

**Comment by sethidden** [comment]
Closing because stale.
